### ISSUE TITLE
Convert set-up doc to markdown

### ISSUE THREAD

**Issue by ijmitch** [cicsdev/cics-liberty-minibank-example#7]
How about converting https://github.com/cicsdev/CICS-Liberty-minibank-example/blob/master/com.ibm.cics.minibank.document/How%20to%20setup%20MiniBank%20in%20your%20own%20environmentV1.0.pdf to be checked-in markdown? The content would then appear directly in the browser rather than needing to click to have the PDF rendered.

**Comment by ibmstormli** [comment]
Is this the markdown you talked about?
https://en.wikipedia.org/wiki/Markdown
I never used it before. I will have a try.

**Comment by chrispoole643** [comment]
Hey Storm, yes, that's the one.

What's the source of the PDF? There are conversion tools available to convert to markdown, if you don't want to do it by hand.

**Comment by chrispoole643** [comment]
Suggested Storm uses [Pandoc](http://pandoc.org/). Let me know how you get on :)

**Comment by ijmitch** [comment]
The last commit message for this directory was to remove a docx version, so sounds like that might be the source.

**Comment by jiangcbj** [comment]
I just add a new markdown version of the setup file. Thanks very much for all your help. -:)

**Comment by ijmitch** [comment]
Nice!

**Comment by markcocker** [comment]
Can this issue be closed now?

**Comment by EvanZhouTHU** [comment]
@markcocker Agree~
